name: Build

on:
  push:
    branches: [master]
  pull_request: {}
  merge_group: {}

jobs:

  build-windows-msys2:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x86_64 GCC
            sys: mingw64
            env: x86_64
            label: win64
          - name: i686 GCC
            sys: mingw32
            env: i686
            pkg: nasm
            label: win32
    name: Windows MSYS2 ${{matrix.name}}
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        cache: true
        install: git mingw-w64-${{matrix.env}}-toolchain make ${{matrix.pkg}}

    - name: build
      run: |
        git fetch --unshallow
        make -j2 duke3d sw blood rr exhumed kenbuild tools SDLCONFIG= ${{matrix.opt}}

    - name: prepare artifacts
      if: github.ref == 'refs/heads/master'
      run: |
        mkdir -p upload/nblood/
        mkdir -p upload/rednukem/
        mkdir -p upload/pcexhumed/
        cp nblood.exe upload/nblood/
        cp rednukem.exe upload/rednukem/
        cp pcexhumed.exe upload/pcexhumed/

    - uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/master'
      with:
        name: ${{matrix.label}}
        path: upload/
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

  build-windows-msys2-testonly:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x86_64 GCC without SDL
            sys: mingw64
            env: x86_64
            opt: RENDERTYPE=WIN
    name: Windows MSYS2 ${{matrix.name}}
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        cache: true
        install: git mingw-w64-${{matrix.env}}-toolchain make ${{matrix.pkg}}

    - name: build
      run: make -j2 duke3d sw blood rr exhumed kenbuild tools SDLCONFIG= ${{matrix.opt}}

  build-linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: GCC
            pkg: libsdl2-dev
          - name: GCC SDL 1.2
            pkg: libsdl1.2-dev
            opt: SDL_TARGET=1
          - name: Clang
            pkg: libsdl2-dev clang
            opt: CLANG=1
          - name: Clang without GL
            pkg: libsdl2-dev clang
            opt: CLANG=1 USE_OPENGL=0
          - name: Clang without Polymer
            pkg: libsdl2-dev clang
            opt: CLANG=1 POLYMER=0
    name: Linux ${{matrix.name}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install-prerequisites
      run: |
        sudo apt-get update
        sudo apt-get -y install libflac-dev libvpx-dev libgtk2.0-dev ${{matrix.pkg}}

    - name: build
      run: make -j2 duke3d sw blood rr exhumed kenbuild tools ${{matrix.opt}}

  build-macos:
    name: macOS Clang
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: install-prerequisites
      run: |
        brew install sdl2 flac libvpx make
        brew unlink lz4

    - name: build
      run: gmake -j2 duke3d sw blood rr exhumed kenbuild tools
